### ISSUE TITLE
Event sent twice

### ISSUE THREAD

**Issue by jeffmaury** [quarkiverse/quarkus-github-app#108]
I started a GitHub app that would listen to workflow completion.
So here's my method:

```
    void onWorkflow(@WorkflowRun.Completed GHEventPayload.WorkflowRun workflowRunPayload) {
        System.out.println("Workflow completed id " + workflowRunPayload.getWorkflowRun().getWorkflowId());
        System.out.println("sha1 " + workflowRunPayload.getWorkflowRun().getHeadSha());
    }
```

But I can see that this method is triggered twice for each workflow run. I can see the events duplicated in the replay log.
I also checked the Smee log and can see that for each workflow run I see both POST request one for started and one for completed

**Comment by gsmet** [comment]
What does the full class look like?

**Comment by jeffmaury** [comment]
```
package com.jeffmaury.github.apps.xunit;

import io.quarkiverse.githubapp.event.WorkflowRun;
import org.kohsuke.github.GHEventPayload;

public class XUnitApp {
    void onWorkflow(@WorkflowRun.Completed GHEventPayload.WorkflowRun workflowRunPayload) {
        System.out.println("Workflow completed id " + workflowRunPayload.getWorkflowRun().getWorkflowId());
        System.out.println("sha1 " + workflowRunPayload.getWorkflowRun().getHeadSha());
    }
}

```

**Comment by gsmet** [comment]
I created a class like this:
```
public class TestWorkflow {

    void workflowRequested(@WorkflowRun.Requested GHEventPayload.WorkflowRun workflowRun) {
        System.out.println("Requested: " + workflowRun.getWorkflowRun().getId());
    }

    void workflowCompleted(@WorkflowRun.Completed GHEventPayload.WorkflowRun workflowRun) {
        System.out.println("Completed: " + workflowRun.getWorkflowRun().getId());
    }
}
```
And the output is:
```
Requested: 693567342
Completed: 693567342
```
So there must be something odd with your setup? You have two events of the exact same type (action included) in the replay UI? Are you sure you haven't set up two different GH Apps pointing to the same smee.io setup?

**Comment by jeffmaury** [comment]
What if you remove the requested method?

**Comment by gsmet** [comment]
I just get:
```
Completed: 694794854
```

If you want, we can have a talk tomorrow so that you can show me your setup and I can check everything is all right.

Basically:
- if you see the exact same event twice in the Replay UI, that means you receive it twice from GitHub (the logic is dead simple there so you can be sure it's received twice if you get two exact identical events)
- if you receive only one event in the Replay Ui and then the method is executed twice, there can be several causes (be sure to make a clean, also your class shouldn't be a bean by itself - we generate a subclass that will be the bean so yours shouldn't be one otherwise things are executed twice - but what you showed me should be good)

**Comment by jeffmaury** [comment]
Found the mistake I did: was confused by smee.io homepage and run the smee client in parallel to `mvn quarkus:dev`
